AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/IndentationWidth:
    Width: 4

Bundler/OrderedGems:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Layout/EmptyLinesAroundClassBody:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Layout/EmptyLinesAroundModuleBody:
    EnforcedStyle: empty_lines

Style/RedundantReturn:
    Enabled: false

Layout/CaseIndentation:
    EnforcedStyle: case
